stages:
  - qa

# Needs variable FLOW to be defined in extending jobs
# This variable must be the absolute path to the job to execute
current_branch_flow:
  stage: qa
  image: 
    name: $CI_REGISTRY/demis-light/demis-profile-loader:latest
    entrypoint: [""]
    pull_policy: always
  # The fetched git repo only has a detached head. 
  # We have to attach it to the branch name for which we execute the pipeline
  script:
    - |
      git checkout -B "$CI_COMMIT_REF_NAME"
      java -jar /workspace/profile-loader.jar \
          -f .ci/notificationApi-current_branch.yaml \
          -l .ci/locations_ci.yaml
