stages:
  - qa


# Needs variable FLOW to be defined in extending jobs
# This variable must be the absolute path to the job to execute
current_branch_flow:
  stage: qa
  image: 
    name: $CI_REGISTRY/demis-light/demis-profile-loader:latest
    entrypoint: [""]
    pull_policy: always
  before_script:
       - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY/demis-light/demis-profile-loader:latest
  script:
    - |
      CI_SIMPLE_BRANCH_NAME=${CI_COMMIT_REF_NAME##*/}
      java -jar /workspace/profile-loader.jar \
          -f .ci/notificationApi-current_branch.yaml \
          -l .ci/locations_ci.yaml
