stages:
  - tmp
  - qa

list_branches:
  variables:
    GIT_STRATEGY: clone
    GIT_FETCH_EXTRA_FLAGS: --all
  image: 
    name: alpine/git:v2.40.1
    entrypoint: [""]
  stage: tmp
  script: git branch -a --format "%(refname) [%(upstream)]"

# Needs variable FLOW to be defined in extending jobs
# This variable must be the absolute path to the job to execute
current_branch_flow:
  stage: qa
  image: 
    name: $CI_REGISTRY/demis-light/demis-profile-loader:latest
    entrypoint: [""]
    pull_policy: always
  variables:
    GIT_STRATEGY: clone
    GIT_FETCH_EXTRA_FLAGS: --all
  script:
    - |
      echo $CI_COMMIT_REF_NAME
      echo $CI_PROJECT_DIR
      ls -la $CI_PROJECT_DIR
      java -jar /workspace/profile-loader.jar \
          -f .ci/notificationApi-current_branch.yaml \
          -l .ci/locations_ci.yaml
