@startuml
title Überblick der EMIGA EINRV Implementierung

class EmigaDepartmentOrganization
class EmigaHealthcareService
class EmigaHospitalFacilityLocation
class EmigaHospitalLocation
class EmigaHospitalOrganization
class EmigaHospitalRoomLocation
class EmigaLocation
class EmigaOrganization
class EmigaPractitioner
class EmigaPractitionerRole
class EmigaPublicHealthLocation
class EmigaPublicHealthOrganization
class IdentifierCodeSiteId

EmigaPublicHealthOrganization--> Organization: Teil von (partOf)
EmigaPublicHealthLocation--> EmigaPublicHealthOrganization : Verwaltende Einrichtung (managingOrganization)
EmigaPublicHealthOrganization--> IdentifierCodeSiteId : besitzt

EmigaPractitionerRole--> EmigaOrganization : Einrichtung, in der die Rolle ausgeübt werden kann
EmigaPractitionerRole--> EmigaPractitioner : Practitioner, der die für die Einrichtung definierten Leistungen erbringen kann
EmigaPractitionerRole--> EmigaHealthcareService : Gesundheitsleistungen, die der Practitioner für die Einrichtung bzw. deren Standorte erbringt

EmigaOrganization--> Organization: Teil von (partOf)
EmigaLocation--> Organization : Verwaltende Einrichtung (managingOrganization)

EmigaHospitalRoomLocation--> EmigaHospitalOrganization : Verwaltende Einrichtung (managingOrganization)
EmigaHospitalRoomLocation--> EmigaHospitalLocation: Teil von (partOf)
EmigaHospitalOrganization--> Organization : Verwaltende Einrichtung (managingOrganization)
EmigaHospitalLocation--> EmigaHospitalOrganization : Verwaltende Einrichtung (managingOrganization)
EmigaHospitalFacilityLocation--> EmigaHospitalOrganization : Verwaltende Einrichtung (managingOrganization)
EmigaHospitalFacilityLocation--> EmigaHospitalLocation: Teil von (partOf)

EmigaHealthcareService--> Organization: bereitgestellt von (providedBy)
EmigaHealthcareService--> EmigaLocation: Referenzierung der Standorte, an denen die Dienstleistung angeboten wird (location)

EmigaDepartmentOrganization--> Organization: Verwaltende Einrichtung (managingOrganization)
@enduml