@startuml
  set namespaceSeparator none
  skinparam backgroundcolor transparent
  skinparam classBackgroundColor #FFFFCC
  skinparam classBorderColor black
  skinparam classAttributeIconSize 1
  skinparam nodesep 50
  skinparam ranksep 50

  class "Standort/Location" <<EmigaLocation>> {
  }

  class "Organisation/Organization" <<EmigaOrganization>> {
  }

  class "Dienstleistung/HealthcareService" <<EmigaealthcareService>> {
  }

  class "EmigaPerson/Practitioner" <<EmigaPractitioner>> {
  }

  class "Rolle/PractitionerRole" <<EmigaPractitionerRole>> {
  }

  ' Lines with arrows (directional relationships)
  "Standort/Location" --> "Organisation/Organization" : 0..1\nLocation.managingOrganization
  "Dienstleistung/HealthcareService" --> "Organisation/Organization" : 1..1\nHealthcareService.providedBy
  "Rolle/PractitionerRole" --> "Organisation/Organization" : 0..1\nPractitionerRole.organization
  "Rolle/PractitionerRole" --> "Standort/Location" : 0..1\nPractitionerRole.location
  "Rolle/PractitionerRole" --> "EmigaPerson/Practitioner" : 0..1\nRole.practitioner

  ' Lines without arrows (associative relationships)
  "Organisation/Organization" -- "Standort/Location" : 0..*\nOrganization.partOf
  "Dienstleistung/HealthcareService" -- "Standort/Location" : 0..*\nHealthcareService.location
  "Rolle/PractitionerRole" -- "Dienstleistung/HealthcareService" : 0..*\nPractitionerRole.healthcareService

@enduml