@startuml
title Überblick der Krankenhaus-Organisationen

top to bottom direction

skinparam shadowing false
skinparam linetype ortho
skinparam defaultTextAlignment left
skinparam ArrowFontSize 11

skinparam nodesep 150
skinparam ranksep 110


rectangle "**EmigaHospitalFacilityLocation**\nKrankenhaus - Einrichtungsstandort bildet Einrichtungen nach InEK-\nStandortverzeichnis oder Stationen eines Krankenhauses ab." as EmigaHospitalFacilityLocation

rectangle "**EmigaHospitalLocation**\nDieses Profil bildet einen Standort eines Krankenhauses im Kontext\nvon EMIGA ab. Es dient der strukturierten Erfassung von besuchbaren\nKrankenhaus-Standorten (z. B. Hauptstandort, Klinikgebäude, Stationen)\neinschließlich Adress- und ggf. Geokoordinaten für die Nutzung in\nMelde-, Dokumentations- und Kommunikationsprozessen." as EmigaHospitalLocation

rectangle "**EmigaHospitalOrganization**\nProfil zur Abbildung eines Krankenhauses im Kontext von EMIGA.\nEs dient der strukturierten Erfassung von Stammdaten des Krankenhauses\n(z. B. Name, Kennziffern, Kontakt- und Adressdaten) für die Nutzung in\nMelde-, Dokumentations- und Kommunikationsprozessen. Wenn ein Krankenhaus\n aus InEK importiert wird dann besizt keine Addresse.\n Die Adressen sind im Standort (EmigaHospitalLocation) zu finden." as EmigaHospitalOrganization

rectangle "**EmigaHospitalRoomLocation**\nDieses Profil bildet einen Raum in einem Krankenhaus im Kontext von\nEMIGA ab. Es dient der strukturierten Erfassung von räumlichen Einheiten\ninnerhalb eines Krankenhausstandorts (z. B. Zimmer, Behandlungsräume,\nIsolationsbereiche) einschließlich ihrer Identifikation und Zuordnung\nzu übergeordneten Organisationseinheiten." as EmigaHospitalRoomLocation


' --------------------------------------------------
' Layout-Steuerung
' --------------------------------------------------

' obere Position
EmigaHospitalLocation -[hidden]down- EmigaHospitalOrganization

' mittlere Reihe
EmigaHospitalFacilityLocation -[hidden]right- EmigaHospitalOrganization
EmigaHospitalOrganization -[hidden]right- EmigaHospitalRoomLocation


' --------------------------------------------------
' Beziehungen
' --------------------------------------------------

' managingOrganization symmetrisch zur Mitte
EmigaHospitalFacilityLocation -right-> EmigaHospitalOrganization : Verwaltende Organisation\n(managingOrganization)

EmigaHospitalRoomLocation -up-> EmigaHospitalOrganization : Verwaltende Organisation\n(managingOrganization)

EmigaHospitalLocation -down-> EmigaHospitalOrganization : Verwaltende Organisation\n(managingOrganization)


' partOf symmetrisch nach oben
EmigaHospitalFacilityLocation -up-> EmigaHospitalLocation : Teil von\n(partOf)

EmigaHospitalRoomLocation -up-> EmigaHospitalLocation : Teil von\n(partOf)

@enduml