@startuml
title Überblick der ÖGD-Organisationen

top to bottom direction

skinparam shadowing false
skinparam linetype ortho
skinparam defaultTextAlignment left
skinparam ArrowFontSize 11

skinparam nodesep 160
skinparam ranksep 180


rectangle "**EmigaPublicHealthOrganization**\nUnter der ÖGD Organisation werden alle Organisationen zusammengefasst,\ndie EMIGA direkt nutzende ÖGD-Organisationen sind, die eine CodeSite-ID besitzen." as EmigaPublicHealthOrganization

rectangle "**IdentifierCodeSiteId**\nIdentifier-Profil für die vom RKI vergebene Kennung der Organisationen\ndes ÖGD (Gesundheitsamt, Landesstelle usw.)." as IdentifierCodeSiteId

rectangle "**EmigaPublicHealthLocation**\nPhysischer Standort eines ÖGD-Fachbereichs, an dem Leistungen erbracht werden.\nDer Standort ist in der Regel über eine Adresse und optional über Geo-Koordinaten\neindeutig räumlich verortet." as EmigaPublicHealthLocation

rectangle "**EmigaPractitioner**\nPerson, die im Kontext des ÖGD Leistungen erbringt bzw. Aufgaben\ninnerhalb einer ÖGD-Organisation wahrnimmt." as EmigaPractitioner

rectangle "**EmigaPractitionerRole**\nBeschreibt die Rolle einer Person innerhalb einer ÖGD-Organisation\nsowie die damit verbundenen organisatorischen und fachlichen Zuordnungen." as EmigaPractitionerRole

rectangle "**EmigaHealthcareService**\nBeschreibung einer Dienstleistung, die durch eine ÖGD-Organisation\nbzw. an deren Standorten angeboten wird." as EmigaHealthcareService


' --------------------------------------------------
' Layout-Steuerung
' --------------------------------------------------

' obere Reihe
EmigaPractitioner -[hidden]right- EmigaPractitionerRole
EmigaPractitionerRole -[hidden]right- EmigaHealthcareService

' zentrale Organisation
EmigaPractitionerRole -[hidden]down- EmigaPublicHealthOrganization

' seitliche Elemente um die Organisation
IdentifierCodeSiteId -[hidden]right- EmigaPublicHealthOrganization
EmigaPublicHealthOrganization -[hidden]right- EmigaPublicHealthLocation


' --------------------------------------------------
' Practitioner / PractitionerRole
' --------------------------------------------------

EmigaPractitionerRole -left-> EmigaPractitioner : Person, der die für die\n Organisation definierten\n Leistungen erbringen kann\n(practitioner)

EmigaPractitionerRole -down-> EmigaPublicHealthOrganization : Organisation, in der die Rolle\nausgeübt werden kann\n(organization)

EmigaPractitionerRole -right-> EmigaHealthcareService : Dienstleistungen,\n die der Practitioner\nfür die Organisation bzw.\n deren Standorte erbringt\n(healthcareService)


' --------------------------------------------------
' HealthcareService
' --------------------------------------------------

EmigaHealthcareService -left-> EmigaPublicHealthOrganization : bereitgestellt von\n(providedBy)

EmigaHealthcareService --> EmigaPublicHealthLocation : Referenzierung der Standorte,\nan denen die Dienstleistung angeboten wird\n(location)


' --------------------------------------------------
' ÖGD Organisation / Standort
' --------------------------------------------------

EmigaPublicHealthOrganization -up-> EmigaPublicHealthOrganization : Teil von\n(partOf)

EmigaPublicHealthLocation -left-> EmigaPublicHealthOrganization : Verwaltende Organisation\n(managingOrganization)

EmigaPublicHealthOrganization -down-> IdentifierCodeSiteId : besitzt

@enduml