@startuml
title Überblick der ÖGD Organisationen

class EmigaPublicHealthOrganization{
Unter der ÖGD Organisation werden alle Organisationen zusammengefasst, die EMIGA
direkt nutzende ÖDG-Organisationen sind, die eine CodeSite-ID besitzen.
}
class IdentifierCodeSiteId{
Identifier-Profil für die vom RKI vergebene Kennung des Organisationen
des ÖGDs (Gesundheitsamts, Landesstelle, usw.).
}
class EmigaPublicHealthLocation{
Physischer Standort eines ÖGD-Fachbereichs, an dem Leistungen erbracht werden. 
Der Standort ist in der Regel über eine Adresse und optional über Geo-Koordinaten
eindeutig räumlich verortet.
}

EmigaPublicHealthOrganization --> Organization : Teil von (partOf)
EmigaPublicHealthLocation --> EmigaPublicHealthOrganization : Verwaltende Organisation (managingOrganization)
EmigaPublicHealthOrganization --> IdentifierCodeSiteId : besitzt

Organization -[hidden]down- EmigaPublicHealthOrganization
EmigaPublicHealthOrganization -[hidden]down- EmigaPublicHealthLocation

@enduml