@startuml
title EmigaHospitalOrganization (Profile of Organization) - Class Diagram

' Main Class
class EmigaHospitalOrganization{
<b>+</b> id: string [0..1]
' TODO die anderen IDs lassen wir weg?
-- Meta --
' TODO lassen wir extension weg?
<b>+</b> meta.lastUpdated: instant [0..1] 
<b>+</b> meta.profile:emigaprofile: canonical(StructureDefinition) [0..*]
<b>+</b> meta.source: uri [0..1] 
<b>+</b> meta.versionId: id [0..1] 
' TODO security hat  0..*, visbility und security haben beide 0..1 -> was wollen wir anzeigen?
<b>+</b> meta.security:responsibility.display: string [0..1]
<b>+</b> meta.security:visibility.display: string [0..1]
' TODO tag hat  0..*, relevance, orgvBundleId und orgvBundleVersion haben 0..1 -> was wollen wir anzeigen?
<b>+</b> meta.tag:orgvBundleId.display: string [0..1] 
<b>+</b> meta.tag:orgvBundleVersion.display: string [0..1] 
<b>+</b> meta.tag:relevance.display: string [0..1] 
-- Identifiers --
' TODO welche Kardinalitäten sind hier richtig? die von value oder die von dem übergeordneten Objekt?
<b>+</b> identifier:BSNR.value: string [0..1] 
<b>+</b> identifier:demisParticipantId.value: string [0..1] 
<b>+</b> identifier:emigaOrgvFileNumber: IdentifierEmigaOrgvFileNumber [1..1] 
<b>+</b> identifier:emigaOrgvId: IdentifierEmigaOrgvId [0..1] 
<b>+</b> identifier:IKNR.value: string [0..1] 
<b>+</b> identifier:telematikID.value: string [0..1] 
-- Organization Information --
<b>+</b> active: boolean [1..1]
<b>+</b> alias: string [0..1]
<b>+</b> extension:inekVersionPeriod: Extension(Complex) [0..1]
<b>+</b> language: code [0..1] 
<b>+</b> name: string [1..1]
<b>+</b> partOf: Reference(Organization) [0..1]
' TODO type hat  1..*, emigaOrganizationType.coding.display hat 0..1 -> was wollen wir anzeigen?
<b>+</b> type:emigaOrganizationType.coding.display: string [0..1]
<b>+</b> type:fachbereich.coding.display: string [0..1]
-- Communication --
<b>+</b> address.city: string [0..1]
<b>+</b> address.country: string [0..1]
<b>+</b> address.extension:Stadtteil: string [0..1]
<b>+</b> address.line.extension:Adresszusatz: string [0..1]
<b>+</b> address.line.extension:Hausnummer: string [0..1]
<b>+</b> address.line.extension:Postfach: string [0..1]
<b>+</b> address.line.extension:Strasse: string [0..1]
<b>+</b> address.line.value: System.string [0..1]
<b>+</b> address.period.end: dateTime [0..1]
<b>+</b> address.period.start: dateTime [0..1]
<b>+</b> address.postalCode: string [0..1]
<b>+</b> address.state: string [0..1]
<b>+</b> address.text: string [0..1]
<b>+</b> address.type: code [0..1]
<b>+</b> address.use: code [0..1]
' TODO welche Kardinalitäten sind korrekt?
<b>+</b> telecom:Email.value: string [0..*]
<b>+</b> telecom:Fax.value: string [0..*]
<b>+</b> telecom:Phone.value: string [0..*]
<b>+</b> telecom:Url.value: string [0..*]
}

@enduml