@startuml
skinparam linetype ortho

title EmigaOrganization (Profile of Organization) - Class Diagram

class EmigaOrganization{
}

class EmigaLocation{
}

class EmigaPractitioner{
}

class EmigaPractitionerRole{
}

EmigaOrganization ..> EmigaOrganization
note on link: partOf

EmigaLocation --> EmigaOrganization
note on link: managingOrganization

EmigaLocation ..> EmigaLocation
note on link: partOf

EmigaPractitionerRole --> EmigaPractitioner
note on link: Reference

EmigaPractitionerRole --> EmigaOrganization
note on link: Reference

EmigaPractitionerRole --> EmigaLocation
note on link: Reference


@enduml
