@startuml
skinparam linetype ortho

title EmigaOrganization (Profile of Organization) - Class Diagram

' Main Class
class EmigaOrganization{
-- Organization Information --
<b>+</b> active: boolean [1..1]
<b>+</b> alias: string [0..1]
<b>+</b> extension:organizationPeriod: Extension(Period) [0..1]
<b>+</b> name: string [1..1]
<b>+</b> partOf: Reference(Organization) [0..1]
<b>+</b> type:emigaOrganizationType: CodeableConcept [1..1]
-- Meta --
<b>+</b> meta.profile:emigaprofile: canonical(StructureDefinition) [0..*]
<b>+</b> meta.security:responsibility: Coding [0..1]
<b>+</b> meta.security:visibility: Coding [0..1]
<b>+</b> meta.tag:orgvBundleId: Coding [0..1]
<b>+</b> meta.tag:orgvBundleVersion: Coding [0..1]
<b>+</b> meta.tag:relevance: Coding [0..*]
-- Identifiers --
<b>+</b> identifier:BSNR: IdentifierBsnr [0..1] 
<b>+</b> identifier:demisLaboratoryId: Identifier [0..1]
<b>+</b> identifier:demisParticipantId: Identifier [0..1]
<b>+</b> identifier:emigaOrgvFileNumber: IdentifierEmigaOrgvFileNumber [0..1]
<b>+</b> identifier:emigaOrgvId: IdentifierEmigaOrgvId [0..1]
<b>+</b> identifier:IKNR: IdentifierIknr [0..1]
<b>+</b> identifier:LANR: IdentifierLanr [0..1]
<b>+</b> identifier:telematikID: IdentifierTelematikId [0..1]
-- Communication --
<b>+</b> address.city: string [0..1]
<b>+</b> address.extension:Stadtteil: Extension(string) [0..1]
<b>+</b> address.line.extension:Adresszusatz: Extension(string) [0..1]
<b>+</b> address.line.extension:Hausnummer: Extension(string) [0..1]
<b>+</b> address.line.extension:Postfach: Extension(string) [0..1]
<b>+</b> address.line.extension:Strasse: Extension(string) [0..1]
<b>+</b> address.postalCode: string [0..1]
<b>+</b> address.state: string [0..1]
<b>+</b> telecom:Email: ContactPoint [0..*]
<b>+</b> telecom:Fax: ContactPoint [0..*]
<b>+</b> telecom:Phone: ContactPoint [0..*]
<b>+</b> telecom:Url: ContactPoint [0..*]
}

@enduml